/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haegg' at '2016-09-30 16:23' with Gradle 2.6
 *
 * @author haegg, @date 2016-09-30 16:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
